# Generated by Django 4.1.4 on 2022-12-27 08:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('hotelname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('longitude', models.FloatField(max_length=255)),
                ('latitude', models.FloatField(max_length=255)),
                ('geopoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
